//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Employees = new HashSet<Employee>();
            Server_Date_Time = DateTime.Now;
            Update_Date_Time_UTC = DateTime.Now;
            Date_Time_UTC = DateTime.Now;
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Server_Date_Time { get; set; }
        public System.DateTime Date_Time_UTC { get; set; }
        public System.DateTime Update_Date_Time_UTC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
