//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            Server_Date_Time = DateTime.Now;
            Update_Date_Time_UTC = DateTime.Now;
            Date_Time_UTC = DateTime.Now;
        }
        public long ID { get; set; }
        public long Department_ID { get; set; }
        public System.DateTime Server_Date_Time { get; set; }
        public System.DateTime Date_Time_UTC { get; set; }
        public System.DateTime? Update_Date_Time_UTC { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Mobile_Number { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
